# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 587)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setGeometry(QtCore.QRect(0, 0, 811, 551))
        self.main_tab.setObjectName("main_tab")
        self.mqtt_tab = QtWidgets.QWidget()
        self.mqtt_tab.setObjectName("mqtt_tab")
        self.main_tab.addTab(self.mqtt_tab, "")
        self.rpc_tab = QtWidgets.QWidget()
        self.rpc_tab.setObjectName("rpc_tab")
        self.main_tab.addTab(self.rpc_tab, "")
        self.http_tab = QtWidgets.QWidget()
        self.http_tab.setObjectName("http_tab")
        self.main_tab.addTab(self.http_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "通用管理工具"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.mqtt_tab), _translate("MainWindow", "MQTT"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.rpc_tab), _translate("MainWindow", "RPC"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.http_tab), _translate("MainWindow", "HTTP"))
