# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpc_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(756, 533)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 191, 121))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 181, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.rpc_host_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rpc_host_label.setObjectName("rpc_host_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rpc_host_label)
        self.rpc_host_text = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rpc_host_text.setObjectName("rpc_host_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rpc_host_text)
        self.rpc_port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rpc_port_label.setObjectName("rpc_port_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rpc_port_label)
        self.rpc_port_text = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rpc_port_text.setObjectName("rpc_port_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rpc_port_text)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 191, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 181, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.rpc_module_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rpc_module_label.setObjectName("rpc_module_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rpc_module_label)
        self.rpc_module_text = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.rpc_module_text.setObjectName("rpc_module_text")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rpc_module_text)
        self.rpc_method_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rpc_method_label.setObjectName("rpc_method_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rpc_method_label)
        self.rpc_method_text = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.rpc_method_text.setObjectName("rpc_method_text")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rpc_method_text)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 10, 261, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rpc_header_key1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.rpc_header_key1.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.rpc_header_key1.setStyleSheet("QLineEdit {\n"
"   border: None;\n"
"   text-align: right;\n"
"   background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"   border: 1px solid #999;\n"
"   border-radius: 5px;\n"
"   background-color: #fff;\n"
"}")
        self.rpc_header_key1.setObjectName("rpc_header_key1")
        self.rpc_header_value1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.rpc_header_value1.setGeometry(QtCore.QRect(112, 20, 141, 20))
        self.rpc_header_value1.setStyleSheet("QLineEdit {\n"
"   border: None;\n"
"   text-align: right;\n"
"   background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"   border: 1px solid #999;\n"
"   border-radius: 5px;\n"
"   background-color: #fff;\n"
"}")
        self.rpc_header_value1.setObjectName("rpc_header_value1")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(92, 20, 16, 16))
        self.label.setStyleSheet("font: 14pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.add_rpc_header_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.add_rpc_header_btn.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.add_rpc_header_btn.setObjectName("add_rpc_header_btn")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 150, 701, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.rpc_request_text = QtWidgets.QTextEdit(self.groupBox_4)
        self.rpc_request_text.setGeometry(QtCore.QRect(10, 20, 681, 111))
        self.rpc_request_text.setObjectName("rpc_request_text")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 310, 701, 201))
        self.groupBox_5.setObjectName("groupBox_5")
        self.rpc_response_text = QtWidgets.QTextEdit(self.groupBox_5)
        self.rpc_response_text.setGeometry(QtCore.QRect(10, 20, 681, 171))
        self.rpc_response_text.setObjectName("rpc_response_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "RPC配置"))
        self.rpc_host_label.setText(_translate("Form", "RPC主机:"))
        self.rpc_port_label.setText(_translate("Form", "RPC端口:"))
        self.groupBox_2.setTitle(_translate("Form", "RPC请求配置"))
        self.rpc_module_label.setText(_translate("Form", "请求模块:"))
        self.rpc_method_label.setText(_translate("Form", "请求方法:"))
        self.groupBox_3.setTitle(_translate("Form", "RPC请求头配置"))
        self.rpc_header_key1.setText(_translate("Form", "Content-Type"))
        self.rpc_header_value1.setText(_translate("Form", "application/json"))
        self.label.setText(_translate("Form", ":"))
        self.add_rpc_header_btn.setText(_translate("Form", "+"))
        self.groupBox_4.setTitle(_translate("Form", "RPC请求参数"))
        self.groupBox_5.setTitle(_translate("Form", "RPC响应结果"))
